2025-05-04 17:23:28 - INFO - Checking for leader...
2025-05-04 17:23:28 - INFO - [SETUP] Lobby server started on port 60000
2025-05-04 17:23:33 - INFO - Leader found: 127.0.0.1:50001
2025-05-04 17:23:33 - INFO - Info came from: 127.0.0.1:50000
2025-05-04 17:25:19 - INFO - [MAIN] Size of request: 80 bytes
2025-05-04 17:25:19 - INFO - [MAIN] Received request: action: JOIN_LOBBY
username: "kenny"

2025-05-04 17:25:19 - INFO - [MAIN] kenny connected.
2025-05-04 17:25:21 - INFO - [MAIN] Size of request: 80 bytes
2025-05-04 17:25:21 - INFO - [MAIN] Received request: action: JOIN_LOBBY
username: "nick"

2025-05-04 17:25:21 - INFO - [MAIN] nick connected.
2025-05-04 17:25:23 - INFO - [MAIN] Size of request: 80 bytes
2025-05-04 17:25:23 - INFO - [MAIN] Received request: action: SEND_VOTE
username: "nick"
vote: true

2025-05-04 17:25:24 - INFO - [MAIN] Size of request: 80 bytes
2025-05-04 17:25:24 - INFO - [MAIN] Received request: action: SEND_VOTE
username: "nick"
vote: true

2025-05-04 17:25:25 - INFO - [MAIN] Size of request: 80 bytes
2025-05-04 17:25:25 - INFO - [MAIN] Received request: action: SEND_VOTE
username: "kenny"
vote: true

2025-05-04 17:25:25 - INFO - [MAIN] Size of request: 80 bytes
2025-05-04 17:25:25 - INFO - [MAIN] Received request: action: SEND_VOTE
username: "kenny"
vote: true

2025-05-04 17:25:49 - INFO - [MAIN] Size of request: 80 bytes
2025-05-04 17:25:49 - INFO - [MAIN] Received request: action: PLAY_MOVE

2025-05-04 17:25:50 - INFO - [MAIN] Size of request: 80 bytes
2025-05-04 17:25:50 - INFO - [MAIN] Received request: action: PLAY_MOVE

2025-05-04 17:25:52 - INFO - [MAIN] Size of request: 80 bytes
2025-05-04 17:25:52 - INFO - [MAIN] Received request: action: PLAY_MOVE

2025-05-04 17:25:57 - INFO - [MAIN] Size of request: 80 bytes
2025-05-04 17:25:57 - INFO - [MAIN] Received request: action: PLAY_MOVE

2025-05-04 17:26:01 - INFO - [MAIN] Size of request: 80 bytes
2025-05-04 17:26:01 - INFO - [MAIN] Received request: action: PLAY_MOVE
player_action: RAISE
amount: 10

2025-05-04 17:26:05 - INFO - [MAIN] Size of request: 80 bytes
2025-05-04 17:26:05 - INFO - [MAIN] Received request: action: PLAY_MOVE

2025-05-04 17:26:06 - INFO - [MAIN] Size of request: 80 bytes
2025-05-04 17:26:06 - INFO - [MAIN] Received request: action: PLAY_MOVE

2025-05-04 17:26:10 - INFO - [MAIN] Size of request: 80 bytes
2025-05-04 17:26:10 - INFO - [MAIN] Received request: action: PLAY_MOVE

2025-05-04 17:26:11 - INFO - [MAIN] Size of request: 80 bytes
2025-05-04 17:26:11 - INFO - [MAIN] Received request: action: PLAY_MOVE

2025-05-04 17:26:12 - INFO - [MAIN] Size of request: 80 bytes
2025-05-04 17:26:12 - INFO - [MAIN] Received request: action: PLAY_MOVE

2025-05-04 17:26:12 - INFO - [MAIN] Size of request: 80 bytes
2025-05-04 17:26:12 - INFO - [MAIN] Received request: action: PLAY_MOVE

2025-05-04 17:26:15 - INFO - [MAIN] Size of request: 80 bytes
2025-05-04 17:26:15 - INFO - [MAIN] Received request: action: PLAY_MOVE
player_action: FOLD

2025-05-04 17:26:16 - INFO - [MAIN] Size of request: 80 bytes
2025-05-04 17:26:16 - INFO - [MAIN] Received request: action: PLAY_MOVE
player_action: FOLD

2025-05-04 17:26:17 - INFO - [MAIN] Size of request: 80 bytes
2025-05-04 17:26:17 - INFO - [MAIN] Received request: action: PLAY_MOVE
player_action: FOLD

2025-05-04 17:26:17 - INFO - [MAIN] Size of request: 80 bytes
2025-05-04 17:26:17 - INFO - [MAIN] Received request: action: PLAY_MOVE
player_action: FOLD

2025-05-04 17:26:18 - ERROR - [MAIN] Error handling requests at line 217: Traceback (most recent call last):
  File "/Users/nickydtricky/Desktop/Harvard/Senior Year/Semester 2/CS2620/cs2620_poker/server_lobby.py", line 902, in handle_requests
    for req in request_iterator:
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError

2025-05-04 17:26:20 - ERROR - [MAIN] Error handling requests at line 217: Traceback (most recent call last):
  File "/Users/nickydtricky/Desktop/Harvard/Senior Year/Semester 2/CS2620/cs2620_poker/server_lobby.py", line 902, in handle_requests
    for req in request_iterator:
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError

2025-05-04 17:26:41 - ERROR - [MAIN] Error handling requests at line 217: Traceback (most recent call last):
  File "/Users/nickydtricky/Desktop/Harvard/Senior Year/Semester 2/CS2620/cs2620_poker/server_lobby.py", line 902, in handle_requests
    for req in request_iterator:
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError

2025-05-04 17:26:42 - ERROR - [MAIN] Error handling requests at line 217: Traceback (most recent call last):
  File "/Users/nickydtricky/Desktop/Harvard/Senior Year/Semester 2/CS2620/cs2620_poker/server_lobby.py", line 902, in handle_requests
    for req in request_iterator:
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/Users/nickydtricky/miniforge3/envs/manim-use/lib/python3.11/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError

